FROM debian:7

RUN apt-get update

# Install LAMP Stack
RUN apt-get install mysql-server php5 apache2 php5-mysql php5-gd php5-ldap php5-curl php5-cli php5-mcrypt


# außerdem
# apt-get install openssh-server phpmyadmin

# wie geht man mit den prompts bei der installation um? (mysql, phpmyadmin)


# und dann noch die ganze konfiguration
# siehe http://wiki.processmaker.com/3.0/ProcessMaker_Debian_Installation

# ich hab keine ahnung wie das geht :D
