# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmucon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('et_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventTypeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_name', models.CharField(max_length=200)),
                ('el_type', models.CharField(max_length=200)),
                ('min_occurs', models.IntegerField()),
                ('max_occurs', models.IntegerField()),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmucon.EventType')),
            ],
        ),
    ]
