# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmucon', '0002_eventquery_eventtype_eventtypeelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('app_uid', models.CharField(max_length=128)),
                ('event', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
                ('waiting', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='et_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='eventtypeelement',
            name='el_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='eventtypeelement',
            name='el_type',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pendingevent',
            name='app_uid',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='pendingevent',
            name='status',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='casevariable',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmucon.EventType'),
        ),
    ]
