# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmucon', '0003_auto_20160718_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='event',
            new_name='event_type',
        ),
    ]
