# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmucon', '0004_auto_20160718_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquery',
            name='email',
            field=models.CharField(default='test@example.com', max_length=128),
        ),
        migrations.AddField(
            model_name='eventquery',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventtypeelement',
            name='el_type',
            field=models.CharField(default='string', max_length=128),
        ),
        migrations.AlterField(
            model_name='eventtypeelement',
            name='max_occurs',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventtypeelement',
            name='min_occurs',
            field=models.IntegerField(default=1),
        ),
    ]
