# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmucon', '0005_auto_20160718_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventquery',
            name='uuid',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
