#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

if [ ! -e ENV ]; then
    ./gen > ENV
fi
docker-compose run deploy
cat ENV
# HACK: Hardcoded container name.
# echo "http://$(docker inspect --format '{{ .NetworkSettings.Networks.unicorndocker_default.IPAddress }}' unicorndocker_tomcat_1):8080/Unicorn/"
